edition = "2021"
version = "Two"
max_width = 120
comment_width = 120
fn_call_width = 100
#blank_lines_upper_bound ?
combine_control_expr = false
#error_on_line_overflow = true
#error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
short_array_element_width_threshold = 20
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
